ncert_data = [
    {
        "standard": 1,
        "subject": "english",
        "chapters": [
            {"name": "two little hands", "number": 101},
            {"name": "greetings", "number": 102},
            {"name": "picture time", "number": 103},
            {"name": "the cap-seller and the monkeys", "number": 104},
            {"name": "a farm", "number": 105},
            {"name": "fun with pictures", "number": 106},
            {"name": "the food we eat", "number": 107},
            {"name": "the four seasons", "number": 108},
            {"name": "anandi's rainbow", "number": 109},
        ],
    },
    {
        "standard": 2,
        "subject": "english",
        "chapters": [
            {"name": "my bicycle", "number": 101},
            {"name": "picture reading", "number": 102},
            {"name": "it is fun", "number": 103},
            {"name": "seeing without seeing", "number": 104},
            {"name": "comeback soon", "number": 105},
            {"name": "between home and school", "number": 106},
            {"name": "this is my town", "number": 107},
            {"name": "a show of clouds", "number": 108},
            {"name": "my name", "number": 109},
            {"name": "the crow", "number": 110},
            {"name": "the smart monkey", "number": 111},
            {"name": "little drops of water", "number": 112},
            {"name": "we're all Indians", "number": 113},
        ],
    },
    {
        "standard": 3,
        "subject": "english",
        "chapters": [
            {"name": "colours", "number": 101},
            {"name": "badal and moti", "number": 102},
            {"name": "best friends", "number": 103},
            {"name": "out in the garden", "number": 104},
            {"name": "talking toys", "number": 105},
            {"name": "paper boats", "number": 106},
            {"name": "the big laddoo", "number": 107},
            {"name": "thank god", "number": 108},
            {"name": "madhu's wish", "number": 109},
            {"name": "night", "number": 110},
            {"name": "chanda mama counts the stars", "number": 112},
            {"name": "chandrayaan", "number": 113},
        ],
    },
    {
        "standard": 4,
        "subject": "english",
        "chapters": [
            {"name": "wake up!", "number": 101},
            {"name": "neha's alarm clock", "number": 101},
            {"name": "noses", "number": 102},
            {"name": "the little fir tree", "number": 102},
            {"name": "run!", "number": 103},
            {"name": "nasruddin's aim", "number": 103},
            {"name": "why?", "number": 104},
            {"name": "alice in wonderland", "number": 104},
            {"name": "don't be afraid of the dark", "number": 105},
            {"name": "helen keller", "number": 105},
            {"name": "hiawatha", "number": 106},
            {"name": "the scholar's mother tongue", "number": 106},
            {"name": "a watering rhyme", "number": 107},
            {"name": "the giving tree", "number": 107},
            {"name": "the donkey", "number": 107},
            {"name": "books", "number": 108},
            {"name": "going to buy a book", "number": 108},
            {"name": "The naughty Boy", "number": 109},
            {"name": "pinocchio", "number": 109},
        ],
    },
    {
        "standard": 4,
        "subject": "evs",
        "chapters": [
            {"name": "going to school", "number": 101},
            {"name": "ear to ear", "number": 102},
            {"name": "a day with nandu", "number": 103},
            {"name": "the story of amrita", "number": 104},
            {"name": "anita and the honeybees", "number": 105},
            {"name": "omana's journey", "number": 106},
            {"name": "from the window", "number": 107},
            {"name": "reaching grandmother's house", "number": 108},
            {"name": "changing families", "number": 109},
            {"name": "hu tu tu, hu tu tu", "number": 110},
            {"name": "the valley of flowers", "number": 111},
            {"name": "changing times", "number": 112},
            {"name": "a river's tale", "number": 113},
            {"name": "basva's farm", "number": 114},
            {"name": "from market to home", "number": 115},
            {"name": "a busy month", "number": 116},
            {"name": "nandita in mumbai", "number": 117},
            {"name": "too much water, too little water", "number": 118},
            {"name": "abdul in the garden", "number": 119},
            {"name": "eating together", "number": 120},
            {"name": "food and fun", "number": 121},
            {"name": "the world in my home", "number": 122},
            {"name": "pochampalli", "number": 123},
            {"name": "home and abroad", "number": 124},
            {"name": "spicy riddles", "number": 125},
            {"name": "defence officer : wahida", "number": 126},
            {"name": "chuskit goes to school", "number": 127},
            {"name": "128", "number": 128},
        ],
    },
    {
        "standard": 5,
        "subject": "english",
        "chapters": [
            {"name": "ice cream man", "number": 101},
            {"name": "wonderful waste", "number": 102},
            {"name": "teamwork", "number": 103},
            {"name": "flying together", "number": 104},
            {"name": "my shadow", "number": 105},
            {"name": "robinson crusoe discovers a footprint", "number": 106},
            {"name": "crying", "number": 107},
            {"name": "my elder brother", "number": 108},
            {"name": "rip wan winkle", "number": 109},
            {"name": "class discussion", "number": 110},
            {"name": "the talkative barber", "number": 111},
            {"name": "topsy-turvy land", "number": 112},
            {"name": "guiliver's travels", "number": 113},
            {"name": "nobody's friend", "number": 114},
            {"name": "the little bully", "number": 115},
            {"name": "sing a song of people", "number": 116},
            {"name": "malu bhalu", "number": 117},
            {"name": "Who will be ningthou", "number": 118},
        ],
    },
    {
        "standard": 5,
        "subject": "evs",
        "chapters": [
            {"name": "super senses", "number": 101},
            {"name": "a snake charmer's story", "number": 102},
            {"name": "from tasting to digesting", "number": 103},
            {"name": "mangoes round the year", "number": 104},
            {"name": "seeds and seeds", "number": 105},
            {"name": "every drop counts", "number": 106},
            {"name": "experiments with water", "number": 107},
            {"name": "a treat for mosquitoes", "number": 108},
            {"name": "up you go!", "number": 109},
            {"name": "walls tell stories", "number": 110},
            {"name": "sunita in space", "number": 111},
            {"name": "what if it finishes ...?", "number": 112},
            {"name": "a shelter so high!", "number": 113},
            {"name": "when the earth shook!", "number": 114},
            {"name": "blow hot, blow cold", "number": 115},
            {"name": "who will do this work?", "number": 116},
            {"name": "across the wall", "number": 117},
            {"name": "no place for us?", "number": 118},
            {"name": "a seed tells a farmer's story", "number": 119},
            {"name": "whose forests?", "number": 120},
            {"name": "like father, like daughter", "number": 121},
            {"name": "on the move again", "number": 122},
        ],
    },
    {
        "standard": 6,
        "subject": "english",
        "chapters": [
            {"name": "who did patrick\u2019s homework?", "number": 101},
            {"name": "a house, a home", "number": 102},
            {"name": "how the dog found himself a new master", "number": 103},
            {"name": "the kite", "number": 104},
            {"name": "taro\u2019s reward", "number": 105},
            {"name": "the quarrel", "number": 106},
            {
                "name": "an indian \u2013 american woman in space: kalpana chawla",
                "number": 107,
            },
            {"name": "beauty", "number": 108},
            {"name": "a different kind of school", "number": 109},
            {"name": "where do all the teachers go?", "number": 110},
            {"name": "who i am", "number": 111},
            {"name": "the wonderful words", "number": 112},
            {"name": "fair play", "number": 113},
            {"name": "vocation", "number": 114},
            {"name": "the banyan tree", "number": 115},
        ],
    },
    {
        "standard": 6,
        "subject": "social science",
        "chapters": [
            {"name": "introduction:what, where, how and when?", "number": 101},
            {"name": "from hunting\u2013gathering to growing food", "number": 102},
            {"name": "in the earliest cities", "number": 103},
            {"name": "what books and burials tell us", "number": 104},
            {"name": "kingdoms, kings and an early republic", "number": 105},
            {"name": "new questions and ideas", "number": 106},
            {"name": "from a kingdom to an empire", "number": 107},
            {"name": "villages, towns and trade", "number": 108},
            {"name": "new empires and kingdoms", "number": 109},
            {"name": "buildings, paintings and books", "number": 110},
            {"name": "the earth in the solar system", "number": 201},
            {"name": "globe : latitudes and longitudes", "number": 202},
            {"name": "motions of the earth", "number": 203},
            {"name": "maps", "number": 204},
            {"name": "major domains of the earth", "number": 205},
            {"name": "our country \u2013 india", "number": 206},
        ],
    },
    {
        "standard": 6,
        "subject": "science",
        "chapters": [
            {"name": "components of food", "number": 101},
            {"name": "sorting materials into groups", "number": 102},
            {"name": "separation of substances", "number": 103},
            {"name": "getting to know plants", "number": 104},
            {"name": "body movements", "number": 105},
            {
                "name": "the living organisms \u2013 characteristics and habitats",
                "number": 106,
            },
            {"name": "motion and measurement of distances", "number": 107},
            {"name": "light, shadows and reflections", "number": 108},
            {"name": "electricity and circuits", "number": 109},
            {"name": "fun with magnets", "number": 110},
            {"name": "air around us", "number": 111},
        ],
    },
    {
        "standard": 7,
        "subject": "english",
        "chapters": [
            {"name": "three questions", "number": 101},
            {"name": "the squirrel", "number": 102},
            {"name": "a gift of chappals", "number": 103},
            {"name": "the rebel", "number": 104},
            {"name": "gopal and the hilsa fish", "number": 105},
            {"name": "the shed", "number": 106},
            {"name": "the ashes that made trees bloom", "number": 107},
            {"name": "chivvy", "number": 108},
            {"name": "quality", "number": 109},
            {"name": "trees", "number": 110},
            {"name": "expert detectives", "number": 111},
            {"name": "mystery of the talking fan", "number": 112},
            {"name": "the invention of vita-wonk", "number": 113},
            {"name": "dad and the cat and the tree", "number": 114},
            {"name": "garden snake", "number": 115},
            {"name": "a homage to our brave soldiers", "number": 116},
            {"name": "meadow surprises", "number": 117},
        ],
    },
    {
        "standard": 7,
        "subject": "social science",
        "chapters": [
            {
                "name": "introduction:tracing changes through a thousand years",
                "number": 101,
            },
            {"name": "kings and kingdoms", "number": 102},
            {"name": "delhi: 12th to 15th century", "number": 103},
            {"name": "the mughals (16th to 17th century)", "number": 104},
            {"name": "tribes, nomads and settled communities", "number": 105},
            {"name": "devotional paths to the divine", "number": 106},
            {"name": "the making of regional cultures", "number": 107},
            {"name": "eighteenth-century political formations", "number": 108},
        ],
    },
    {
        "standard": 7,
        "subject": "social science geography",
        "chapters": [
            {"name": "environment", "number": 201},
            {"name": "inside our earth", "number": 202},
            {"name": "our changing earth", "number": 203},
            {"name": "air", "number": 204},
            {"name": "water", "number": 205},
            {
                "name": "human environment interactions the tropical and the subtropical region",
                "number": 206,
            },
            {"name": "life in the deserts", "number": 207},
        ],
    },
    {
        "standard": 7,
        "subject": "science",
        "chapters": [
            {"name": "nutrition in plants", "number": 101},
            {"name": "nutrition in animals", "number": 102},
            {"name": "heat", "number": 103},
            {"name": "acids, bases and salts", "number": 104},
            {"name": "physical and chemical changes", "number": 105},
            {"name": "respiration in organisms", "number": 106},
            {"name": "transportation in animals and plants", "number": 107},
            {"name": "motion and time", "number": 108},
            {"name": "electric current and its effects", "number": 109},
            {"name": "light", "number": 110},
            {"name": "forests: our lifeline", "number": 111},
            {"name": "wastewater story", "number": 112},
        ],
    },
    {
        "standard": 8,
        "subject": "english",
        "chapters": [
            {"name": "the best christmas present 9 in the world", "number": 101},
            {"name": "the ant and the cricket", "number": 102},
            {"name": "the tsunami", "number": 103},
            {"name": "geography lesson", "number": 104},
            {"name": "glimpses of the past", "number": 105},
            {"name": "bepin choudhury\u2019s lapse of memory", "number": 106},
            {"name": "the last bargain", "number": 107},
            {"name": "the summit within", "number": 108},
            {"name": "the school boy", "number": 109},
            {"name": "this is jody\u2019s fawn", "number": 110},
            {"name": "a visit to cambridge", "number": 111},
            {"name": "a short monsoon diary", "number": 112},
            {"name": "on the grasshopper and cricket", "number": 113},
        ],
    },
    {
        "standard": 8,
        "subject": "english",
        "chapters": [
            {"name": "the best christmas present 9 in the world", "number": 101},
            {"name": "the ant and the cricket", "number": 102},
            {"name": "the tsunami", "number": 103},
            {"name": "geography lesson", "number": 104},
            {"name": "glimpses of the past", "number": 105},
            {"name": "bepin choudhury\u2019s lapse of memory", "number": 106},
            {"name": "the last bargain", "number": 107},
            {"name": "the summit within", "number": 108},
            {"name": "the school boy", "number": 109},
            {"name": "this is jody\u2019s fawn", "number": 110},
            {"name": "a visit to cambridge", "number": 111},
            {"name": "a short monsoon diary", "number": 112},
            {"name": "on the grasshopper and cricket", "number": 113},
        ],
    },
    {
        "standard": 8,
        "subject": "social science",
        "chapters": [
            {"name": "introduction: how, when and where", "number": 201},
            {
                "name": "from trade to territory the company establishes power",
                "number": 202,
            },
            {"name": "ruling the countryside", "number": 203},
            {"name": "tribals, dikus and the vision of a golden age", "number": 204},
            {"name": "when people rebel 1857 and after", "number": 205},
            {
                "name": "civilising the \u201cnative\u201d, educating the nation",
                "number": 206,
            },
            {"name": "women, caste and reform", "number": 207},
            {"name": "the making of the national movement: 1870s-–1947", "number": 208},
        ],
    },
    {
        "standard": 8,
        "subject": "social science geography",
        "chapters": [
            {"name": "resources", "number": 401},
            {
                "name": "land, soil, water, natural vegetation and wildlife resources",
                "number": 402,
            },
            {"name": "agriculture", "number": 403},
            {"name": "industries", "number": 404},
            {"name": "human resources", "number": 405},
        ],
    },
    {
        "standard": 8,
        "subject": "science",
        "chapters": [
            {"name": "crop production and management", "number": 101},
            {"name": "microorganisms : friend and foe", "number": 102},
            {"name": "coal and petroleum", "number": 103},
            {"name": "combustion and flame", "number": 104},
            {"name": "conservation of plants and animals", "number": 105},
            {"name": "reproduction in animals", "number": 106},
            {"name": "reaching the age of adolescence", "number": 107},
            {"name": "force and pressure", "number": 108},
            {"name": "friction", "number": 109},
            {"name": "sound", "number": 110},
            {"name": "chemical effects of electric current", "number": 111},
            {"name": "some natural phenomena", "number": 112},
            {"name": "light", "number": 113},
        ],
    },
    {
        "standard": 9,
        "subject": "english",
        "chapters": [
            {"name": "the fun they had", "number": 101},
            {"name": "the sound of music", "number": 102},
            {"name": "the little girl", "number": 103},
            {"name": "a truly beautiful mind", "number": 104},
            {"name": "the snake and the mirror", "number": 105},
            {"name": "my childhood", "number": 106},
            {"name": "reach for the top", "number": 107},
            {"name": "kathmandu", "number": 108},
            {"name": "if i were you", "number": 109},
        ],
    },
    {
        "standard": 9,
        "subject": "social science",
        "chapters": [
            {"name": "the french revolution", "number": 301},
            {"name": "socialism in europe and the russian revolution 2", "number": 302},
            {"name": "nazism and the rise of hitler", "number": 303},
            {"name": "forest society and colonialism", "number": 304},
            {"name": "pastoralists in the modern world", "number": 305},
        ],
    },
    {
        "standard": 9,
        "subject": "social science geography",
        "chapters": [
            {"name": "india \u2013 size and location", "number": 101},
            {"name": "physical features of india", "number": 102},
            {"name": "drainage", "number": 103},
            {"name": "climate", "number": 104},
            {"name": "natural vegetation and wildlife", "number": 105},
            {"name": "population", "number": 106},
        ],
    },
    {
        "standard": 9,
        "subject": "science",
        "chapters": [
            {"name": "matter in our surroundings", "number": 101},
            {"name": "is matter around us pure?", "number": 102},
            {"name": "atoms and molecules", "number": 103},
            {"name": "structure of the atom", "number": 104},
            {"name": "the fundamental unit of life", "number": 105},
            {"name": "tissues", "number": 106},
            {"name": "motion", "number": 107},
            {"name": "force and laws of motion", "number": 108},
            {"name": "gravitation", "number": 109},
            {"name": "work and energy", "number": 110},
            {"name": "sound", "number": 111},
            {"name": "improvement in food resource", "number": 112},
        ],
    },
    {
        "standard": 10,
        "subject": "english",
        "chapters": [
            {"name": "a letter to god", "number": 101},
            {"name": "nelson mandela a long walk to freedom", "number": 102},
            {"name": "two stories about flying", "number": 103},
            {"name": "from the diary of anne frank", "number": 104},
            {"name": "glimpses of india", "number": 105},
            {"name": "mijbil the otter", "number": 106},
            {"name": "madam rides the bus", "number": 107},
            {"name": "the sermon at benaras", "number": 108},
            {"name": "the proposal", "number": 109},
        ],
    },
    {
        "standard": 10,
        "subject": "social science",
        "chapters": [
            {"name": "the rise of nationalisation in europe", "number": 301},
            {"name": "nationalism in india", "number": 302},
            {"name": "the making of a global world", "number": 303},
            {"name": "the age of industrialisation", "number": 304},
            {"name": "print culture and mordern world", "number": 305},
        ],
    },
    {
        "standard": 10,
        "subject": "social science geography",
        "chapters": [
            {"name": "resources and development", "number": 101},
            {"name": "forest and wildlife resources", "number": 102},
            {"name": "water resources", "number": 103},
            {"name": "agriculture", "number": 104},
            {"name": "minerals and energy resources", "number": 105},
            {"name": "manufacturing industries", "number": 106},
            {"name": "lifelines of national economy", "number": 107},
        ],
    },
    {
        "standard": 10,
        "subject": "science",
        "chapters": [
            {"name": "chemical reactions and equations", "number": 101},
            {"name": "acids, bases and salts", "number": 102},
            {"name": "metals and non-metals", "number": 103},
            {"name": "carbon and its compounds", "number": 104},
            {"name": "life processes", "number": 105},
            {"name": "control and coordination", "number": 106},
            {"name": "how do organisms reproduce?", "number": 107},
            {"name": "heredity", "number": 108},
            {"name": "light – reflection and refraction", "number": 109},
            {"name": "the human eye and the colourful world", "number": 110},
            {"name": "electricity", "number": 111},
            {"name": "magnetic effects of electric current", "number": 112},
            {"name": "our environment", "number": 113},
        ],
    },
]
