[tool.poetry]
name = "github-contributions"
version = "0.1.0"
description = "Queries Github's GraphQL API for user contributions to external repos"
authors = ["Mauricio Curiel"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
uagents = "*"
uagents-ai-engine = "^0.1.2"
requests = "^2.26.0"
pydantic = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
