[tool.poetry]
name = "stable-diffusion-v1-4-integration"
version = "1.0.0"
description = "Integrating Stable Diffusion v1-4 with UAgents"
authors = ["Prajna"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
uagents = "*"
requests = "^2.31.0"
pillow = "^10.0.0"
