CAMBRIDGE_RESTAURANT = [
    {
        "name": "Midsummer House",
        "available_table": "2",
        "status": "free",
        "latitude": 52.212910,
        "longitude": 0.128720,
        "distance": 0.2,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Italian",
        "rating": "3.5 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "Fitzbillies",
        "available_table": "3",
        "status": "free",
        "latitude": 52.201950,
        "longitude": 0.118150,
        "distance": 0.9,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "The Eagle",
        "available_table": "4",
        "status": "free",
        "latitude": 52.203900,
        "longitude": 0.117920,
        "distance": 3,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Italian",
        "rating": "4.5 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "La Margherita",
        "available_table": "2",
        "status": "free",
        "latitude": 52.210640,
        "longitude": 0.115210,
        "distance": 4,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "Cotto",
        "available_table": "2",
        "status": "free",
        "latitude": 52.205420,
        "longitude": 0.134460,
        "distance": 5,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegetarian",
        "rating": "5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "St. John's Chop House",
        "available_table": "2",
        "status": "free",
        "latitude": 52.210730,
        "longitude": 0.115020,
        "distance": 2,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegan",
        "rating": "4.5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "Navadhanya",
        "available_table": "2",
        "status": "free",
        "latitude": 52.208470,
        "longitude": 0.136110,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Italian",
        "rating": "5 star",
        "dietary_restrictions": "Dairy Free"
    },
    {
        "name": "The Oak Bistro",
        "available_table": "2",
        "status": "free",
        "latitude": 52.199340,
        "longitude": 0.127240,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Lebanese",
        "rating": "4 star",
        "dietary_restrictions": "Dairy Free"
    }
]
MUNICH_RESTAURANT = [
    {
        "name": "Hofbräuhaus München",
        "available_table": "2",
        "status": "free",
        "latitude": 48.137664,
        "longitude": 11.579376,
        "distance": 0.2,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Italian",
        "rating": "3.5 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "Augustiner-Keller",
        "available_table": "3",
        "status": "free",
        "latitude": 48.137154,
        "longitude": 11.576124,
        "distance": 0.9,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "Schneider Bräuhaus",
        "available_table": "4",
        "status": "free",
        "latitude": 48.136490,
        "longitude": 11.578500,
        "distance": 3,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Italian",
        "rating": "4.5 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "Andechser am Dom",
        "available_table": "2",
        "status": "free",
        "latitude": 48.115000,
        "longitude": 11.576100,
        "distance": 4,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "Viktualienmarkt",
        "available_table": "2",
        "status": "free",
        "latitude": 48.135450,
        "longitude": 11.576340,
        "distance": 5,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegetarian",
        "rating": "5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "Tantris",
        "available_table": "2",
        "status": "free",
        "latitude": 48.169842,
        "longitude": 11.588350,
        "distance": 2,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegan",
        "rating": "4.5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "Alois Dallmayr",
        "available_table": "2",
        "status": "free",
        "latitude": 48.138380,
        "longitude": 11.577350,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Italian",
        "rating": "5 star",
        "dietary_restrictions": "Dairy Free"
    },
    {
        "name": "Tian Restaurant",
        "available_table": "2",
        "status": "free",
        "latitude": 48.134430,
        "longitude": 11.575960,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Lebanese",
        "rating": "4 star",
        "dietary_restrictions": "Dairy Free"
    }
]
PRAGUE_RESTAURANT = [
    {
        "name": "Restaurant Zapomenuty Cas",
        "available_table": "2",
        "status": "free",
        "latitude": 50.0764,
        "longitude": 14.4343,
        "distance": 0.2,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Italian",
        "rating": "3.5 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "Restaurant Pepř a Sůl",
        "available_table": "3",
        "status": "free",
        "latitude": 50.1115,
        "longitude": 14.5005,
        "distance": 0.9,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "King Solomon - Glatt Kosher Restaurant",
        "available_table": "4",
        "status": "free",
        "latitude": 50.0755,
        "longitude": 14.4378,
        "distance": 3,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Italian",
        "rating": "4.5 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "U Tri jelinku",
        "available_table": "2",
        "status": "free",
        "latitude": 50.0887,
        "longitude": 14.4018,
        "distance": 4,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "The Eatery",
        "available_table": "2",
        "status": "free",
        "latitude": 50.1075,
        "longitude": 14.4508,
        "distance": 5,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegetarian",
        "rating": "5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "La Finestra in Cucina",
        "available_table": "2",
        "status": "free",
        "latitude": 50.1075,
        "longitude": 14.4508,
        "distance": 2,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegan",
        "rating": "4.5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "Le Grill Restaurant",
        "available_table": "2",
        "status": "free",
        "latitude": 50.1075,
        "longitude": 14.4508,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Italian",
        "rating": "5 star",
        "dietary_restrictions": "Dairy Free"
    },
    {
        "name": "Agave Restaurant",
        "available_table": "2",
        "status": "free",
        "latitude": 50.1075,
        "longitude": 14.4508,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Lebanese",
        "rating": "4 star",
        "dietary_restrictions": "Dairy Free"
    }
]
STUTTGART_RESTAURANT = [
    {
        "name": "Cube Restaurant",
        "available_table": "2",
        "status": "free",
        "latitude": 48.778370,
        "longitude": 9.177440,
        "distance": 0.2,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Italian",
        "rating": "3.5 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "Amador Restaurant",
        "available_table": "3",
        "status": "free",
        "latitude": 48.771710,
        "longitude": 9.178590,
        "distance": 0.9,
        "additional_amenities": "Online Ordering",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Vegetarian"
    },
    {
        "name": "Speisemeisterei",
        "available_table": "4",
        "status": "free",
        "latitude": 48.804940,
        "longitude": 9.219760,
        "distance": 3,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Italian",
        "rating": "4.5 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "Restaurant Délice",
        "available_table": "2",
        "status": "free",
        "latitude": 48.776210,
        "longitude": 9.165140,
        "distance": 4,
        "additional_amenities": "Private Dining Rooms",
        "cuisine_type": "Chinese",
        "rating": "3 star",
        "dietary_restrictions": "Gluten Free"
    },
    {
        "name": "5 - DAS PINO",
        "available_table": "2",
        "status": "free",
        "latitude": 48.774490,
        "longitude": 9.171460,
        "distance": 5,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegetarian",
        "rating": "5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "Restaurant Christophorus",
        "available_table": "2",
        "status": "free",
        "latitude": 48.737450,
        "longitude": 9.111620,
        "distance": 2,
        "additional_amenities": "Special Dietary Menus",
        "cuisine_type": "Vegan",
        "rating": "4.5 star",
        "dietary_restrictions": "Vegan"
    },
    {
        "name": "Weinstube Fröhlich",
        "available_table": "2",
        "status": "free",
        "latitude": 48.781210,
        "longitude": 9.188600,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Italian",
        "rating": "5 star",
        "dietary_restrictions": "Dairy Free"
    },
    {
        "name": "Restaurant Skyline",
        "available_table": "2",
        "status": "free",
        "latitude": 48.783600,
        "longitude": 9.179580,
        "distance": 2.2,
        "additional_amenities": "Outdoor Seating",
        "cuisine_type": "Lebanese",
        "rating": "4 star",
        "dietary_restrictions": "Dairy Free"
    }
]
