[tool.poetry]
name = "youtube shorts content generator"
version = "0.1.0"
description = ""
authors = ["Aleen Dhar <aleendhar23@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
google-generativeai = "^0.4.1"
transformers = "^4.39.2"
elevenlabs = "^1.0.3"
cloudinary = "^1.39.1"
uagents ="^0.11.0"
uagents-ai-engine = "^0.1.2"
pytest-shutil = "^1.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
