[tool.poetry]
name = "travel-agent"
version = "0.1.0"
description = ""
authors = ["shukabum <s_sharma2@me.iitr.ac.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
