name: ☝️Feature request
description: Suggest an idea for the uAgents Framework.
title: "Feature request"
labels: ["enhancement", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new idea for uAgents! Please complete the following to ensure we have all the details to get things started.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting a feature request.
      options:
        - label: I checked the [documentation ↗️](https://fetch.ai/docs) and made sure this feature does not already exist.
          required: true
        - label: I checked the [existing issues ↗️](https://github.com/fetchai/uAgents/issues) to make sure this feature has not already been requested.
          required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: |
        Provide a description of the feature you would like to see implemented within the uAgents Framework.
    validations:
      required: false
  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: |
        Add any other context, screenshots, or information that could be helpful for understanding your feature request.
    validations:
      required: false
