name: 🐛 Bug Report
description: Report a bug for uAgents.
title: "Bug report: <short description>"
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in uAgents! We appreciate your contribution to improving the library.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting any new issue.
      options:
        - label: I checked the [documentation ↗️](https://fetch.ai/docs) and found no answer to my problem.
          required: true
        - label: I checked the [existing issues ↗️](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug report.
          required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best describes the bug.
      options:
        - label: Bug (unexpected behavior).
        - label: Documentation Issue (error or unclear information in docs).
        - label: Other.
      validations:
        required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe the behavior you are expecting.
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Observed Behavior
      description: Describe the behavior you are observing.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Provide steps to reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: uAgents Version
      description: Which version of uAgents were you using? Please enter the version number here.
      validations:
        required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details (Optional)
      description: Provide any relevant information about your environment, such as operating system, Python version, and any other libraries used.
      render: markdown
      validations:
        required: false
  - type: textarea
    id: logs
    attributes:
      label: Failure Logs (Optional)
      description: Include any relevant log snippets or files here. You can paste directly or drag and drop files into this area.
    render: shell
    validations:
        required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information (Optional)
      description: Include any screenshots, code snippets, or other relevant details that might help us understand the bug.
      render: markdown
      validations:
        required: false
