[tool.poetry]
name = "langchain-rag"
version = "0.1.0"
description = "langchain-rag-uagent-integration"
authors = ["Fetch.AI Limited"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
uagents = "*"
langchain = "^0.1.7"
openai = "^1.12.0"
langchain-openai = "^0.0.6"
faiss-cpu = "^1.7.4"
uagents-ai-engine = "^0.1.2"
notion-client = "^2.2.1"
