[tool.poetry]
name = "multi-lingual-video-agent"
version = "0.1.0"
description = "Agent that can summarize a video in different languages from english"
authors = ["Lenin Kennedy <leninkennedy4work@gmail.com>", "Samuela Abigail Mathew <msamuelaabigail@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
uagents = "0.11.0"
youtube-transcript-api = "^0.6.2"
langchain = "^0.1.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
