apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uagent.fullname" . }}-secrets
  labels:
    {{- include "uagent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.agent.seed }}
  UAGENT_SEED: {{ .Values.agent.seed | b64enc | quote }}
  {{- end }}
